install: fix fail task to work with ansible 2.1
AerisCloud/AerisCloud pull request #37
Opened 2017-02-09 11:14 UTC by tokyowizard

Fixes this error:
```
The error appears to have been in '/opt/aeriscloud/scripts/install/roles/vagrant/tasks/main.yml': line 48, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- fail: "Vagrant must be installed"
  ^ here
```

When installing with:
```
sudo git clone https://github.com/aeriscloud/aeriscloud.git /opt/aeriscloud
sudo chown -R vagrant /opt/aeriscloud
cd /opt/aeriscloud
export AC_NO_ASSISTANT=1
make install
```

2017-02-09 11:24 UTC, MiLk requested changes

2017-02-09 11:24 UTC, MiLk commented on scripts/install/roles/vagrant/tasks/main.yml
> +- fail: msg="Vagrant must be installed"
Can we use the YAML object format as everywhere else on this file instead of the custom ansible stuff which works only when the parser is not broken?

2017-02-09 11:35 UTC, tokyowizard commented on scripts/install/roles/vagrant/tasks/main.yml
> +- fail: msg="Vagrant must be installed"
Yes. I'll fix it now.

2017-02-10 01:03 UTC, MiLk approved these changes

2017-02-10 01:04 UTC, MiLk commented
I would feel safer if @christopherobin could confirm it's working as expected.

2017-02-10 02:21 UTC, christopherobin commented
Yes that's the right way to use fail in 2+, either `fail: msg="something"` or
```yaml
fail:
  msg: something
```

2017-02-10 02:28 UTC, christopherobin approved these changes

2017-02-10 03:03 UTC, merged